# Generated by Django 4.1.5 on 2023-01-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0002_rename_name_person_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Person_name',
            new_name='Person_age',
        ),
    ]
